title: FinalFantasy.se - Sveriges inofficiella guide
email: jonny.stromberg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sveriges inofficiella guide till Final Fantasy som aldrig blir klar. Grundades 2004 av Jonny Strömberg @javve.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://finalfantasy.se" # the base hostname & protocol for your site
twitter_username: javve
github_username:  javve

permalink: pretty
markdown: kramdown
gems:
 - jekyll-coffeescript
 - jekyll-redirect-from

collections:
  xv:
    output: true
