title: FinalFantasy.se - Sveriges inofficiella guide
email: jonny.stromberg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://finalfantasy.se" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  javve

markdown: kramdown
gems:
 - jekyll-coffeescript
 - jekyll-redirect-from

collections:
  xv:
    output: true
